# Form implementation generated from reading ui file 'New_version.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(299, 400)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_result = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(-1, 0, 300, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_result.setFont(font)
        self.label_result.setStyleSheet("background-color: rgb(254, 180, 151);\n"
"color: rgb(0, 0, 0);")
        self.label_result.setObjectName("label_result")
        self.Button_zero = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Button_zero.setGeometry(QtCore.QRect(0, 320, 150, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Button_zero.setFont(font)
        self.Button_zero.setStyleSheet("background-color: rgb(255, 220, 181);")
        self.Button_zero.setObjectName("Button_zero")
        self.Button__equal = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Button__equal.setGeometry(QtCore.QRect(150, 320, 150, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.Button__equal.setFont(font)
        self.Button__equal.setStyleSheet("background-color: rgb(254, 161, 103);")
        self.Button__equal.setObjectName("Button__equal")
        self.Button_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Button_3.setGeometry(QtCore.QRect(160, 240, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Button_3.setFont(font)
        self.Button_3.setStyleSheet("background-color: rgb(255, 220, 181);")
        self.Button_3.setObjectName("Button_3")
        self.Button_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Button_2.setGeometry(QtCore.QRect(80, 240, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Button_2.setFont(font)
        self.Button_2.setStyleSheet("background-color: rgb(255, 220, 181);")
        self.Button_2.setObjectName("Button_2")
        self.Button_1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Button_1.setGeometry(QtCore.QRect(0, 240, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Button_1.setFont(font)
        self.Button_1.setStyleSheet("background-color: rgb(255, 220, 181);")
        self.Button_1.setObjectName("Button_1")
        self.Button_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Button_4.setGeometry(QtCore.QRect(0, 160, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Button_4.setFont(font)
        self.Button_4.setStyleSheet("background-color: rgb(255, 220, 181);")
        self.Button_4.setObjectName("Button_4")
        self.Button_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Button_5.setGeometry(QtCore.QRect(80, 160, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Button_5.setFont(font)
        self.Button_5.setStyleSheet("background-color: rgb(255, 220, 181);")
        self.Button_5.setObjectName("Button_5")
        self.Button_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Button_6.setGeometry(QtCore.QRect(160, 160, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Button_6.setFont(font)
        self.Button_6.setStyleSheet("background-color: rgb(255, 220, 181);")
        self.Button_6.setObjectName("Button_6")
        self.Button_7 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Button_7.setGeometry(QtCore.QRect(0, 80, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Button_7.setFont(font)
        self.Button_7.setStyleSheet("background-color: rgb(255, 220, 181);")
        self.Button_7.setObjectName("Button_7")
        self.Button_8 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Button_8.setGeometry(QtCore.QRect(80, 80, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Button_8.setFont(font)
        self.Button_8.setStyleSheet("background-color: rgb(255, 220, 181);")
        self.Button_8.setObjectName("Button_8")
        self.Button_9 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Button_9.setGeometry(QtCore.QRect(160, 80, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Button_9.setFont(font)
        self.Button_9.setStyleSheet("background-color: rgb(255, 220, 181);")
        self.Button_9.setObjectName("Button_9")
        self.Button_plus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Button_plus.setGeometry(QtCore.QRect(240, 80, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.Button_plus.setFont(font)
        self.Button_plus.setStyleSheet("background-color: rgb(255, 220, 181);")
        self.Button_plus.setObjectName("Button_plus")
        self.Button_minus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Button_minus.setGeometry(QtCore.QRect(240, 140, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.Button_minus.setFont(font)
        self.Button_minus.setStyleSheet("background-color: rgb(255, 220, 181);")
        self.Button_minus.setObjectName("Button_minus")
        self.Button_multi = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Button_multi.setGeometry(QtCore.QRect(240, 200, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.Button_multi.setFont(font)
        self.Button_multi.setStyleSheet("background-color: rgb(255, 220, 181);")
        self.Button_multi.setObjectName("Button_multi")
        self.Button_div = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Button_div.setGeometry(QtCore.QRect(240, 260, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.Button_div.setFont(font)
        self.Button_div.setStyleSheet("background-color: rgb(255, 220, 181);")
        self.Button_div.setObjectName("Button_div")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()
        self.is_equal = False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.label_result.setText(_translate("MainWindow", "0"))
        self.Button_zero.setText(_translate("MainWindow", "0"))
        self.Button__equal.setText(_translate("MainWindow", "="))
        self.Button_3.setText(_translate("MainWindow", "3"))
        self.Button_2.setText(_translate("MainWindow", "2"))
        self.Button_1.setText(_translate("MainWindow", "1"))
        self.Button_4.setText(_translate("MainWindow", "4"))
        self.Button_5.setText(_translate("MainWindow", "5"))
        self.Button_6.setText(_translate("MainWindow", "6"))
        self.Button_7.setText(_translate("MainWindow", "7"))
        self.Button_8.setText(_translate("MainWindow", "8"))
        self.Button_9.setText(_translate("MainWindow", "9"))
        self.Button_plus.setText(_translate("MainWindow", "+"))
        self.Button_minus.setText(_translate("MainWindow", "-"))
        self.Button_multi.setText(_translate("MainWindow", "*"))
        self.Button_div.setText(_translate("MainWindow", "/"))

    def add_functions(self):
        self.Button_zero.clicked.connect(lambda: self.write_number(self.Button_zero.text()))
        self.Button_1.clicked.connect(lambda: self.write_number(self.Button_1.text()))
        self.Button_2.clicked.connect(lambda: self.write_number(self.Button_2.text()))
        self.Button_3.clicked.connect(lambda: self.write_number(self.Button_3.text()))
        self.Button_4.clicked.connect(lambda: self.write_number(self.Button_4.text()))
        self.Button_5.clicked.connect(lambda: self.write_number(self.Button_5.text()))
        self.Button_6.clicked.connect(lambda: self.write_number(self.Button_6.text()))
        self.Button_7.clicked.connect(lambda: self.write_number(self.Button_7.text()))
        self.Button_8.clicked.connect(lambda: self.write_number(self.Button_8.text()))
        self.Button_9.clicked.connect(lambda: self.write_number(self.Button_9.text()))
        self.Button_plus.clicked.connect(lambda: self.write_number(self.Button_plus.text()))
        self.Button_minus.clicked.connect(lambda: self.write_number(self.Button_minus.text()))
        self.Button_multi.clicked.connect(lambda: self.write_number(self.Button_multi.text()))
        self.Button_div.clicked.connect(lambda: self.write_number(self.Button_div.text()))

        self.Button__equal.clicked.connect(self.results)

    def write_number(self, number):
        if self.label_result.text() == "0" or self.is_equal:
            self.label_result.setText(number)
            self.is_equal = False
        else:
            self.label_result.setText(self.label_result.text() + number)

    def results(self):
        if not self.is_equal:
            if "/" in self.label_result.text() and self.label_result.text().split("/")[1] == "0":
                self.label_result.setText("Ошибка")
                self.is_equal = True
                return
        
            res = eval(self.label_result.text())
            self.label_result.setText(str(res))
            self.is_equal = True
        else:
            error = QMessageBox()
            error.setWindowTitle("Ошибка")
            error.setText("Не удается выполнить действие")
            error.setIcon(QMessageBox.Icon.Warning)
            error.setStandardButtons(QMessageBox.StandardButton.Reset|QMessageBox.StandardButton.Ok|QMessageBox.StandardButton.Cancel)

            error.setDefaultButton(QMessageBox.StandardButton.Ok)

            error.buttonClicked.connect(self.popup_action)

            error.exec()
    
    def popup_action(self, btn):
        if btn.text() == "OK":
            print("Print ok")
        elif btn.text() == "Reset":
            self.label_result.setText("")
            self.is_equal = False

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
